title: "Kinematic Tracker Documentation"
author: Peter Koval
description: "Little examples deployed on GitHub pages."
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme  # <--- IMPORTANT: You must add this plugin!

# This ensures GitHub recognizes your code blocks correctly
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax  # Tells Jekyll to leave math blocks alone

